### ISSUE TITLE
Maintaner Wanted!

### ISSUE THREAD

**Issue by tsujigiri** [tsujigiri/axiom#28]
As some of you may have noticed, there hasn't been much going on in this repository for a while. At the same time there are a bunch of forks and dependencies to update. If anyone would be interested in maintaining the project in the future, let me know!

**Comment by jxub** [comment]
Hi @tsujiguri, I might be interested. What are community's plans with regards to axiom?
I made a PR with the updated dependencies which solves the failing build.

**Comment by tsujigiri** [comment]
There isn't much in terms of a community (that I know of :wink:). My approach was to keep it minimal but extendable (see the session store for example). I planned on adding a behavior for that, but never did. Just keeping the dependencies up to date is already great! :slightly_smiling_face:

**Comment by iredmail** [comment]
Glad to know that someone is interested to step in.
It's too sad to watch many open source softwares dying slowly due to lack of maintainer.

**Comment by wizardbeard** [comment]
@tsujigiri - I am very interested in maintaining Axiom - it is exactly what I'm looking for in an Erlang powered framework.

**Comment by tsujigiri** [comment]
@wizardbeard Cool! Do you want to fork it and I put a note into the README?
